package gows

import (
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestExportedDocumentationContract(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatal(err)
	}

	fset := token.NewFileSet()
	var issues []string
	for _, entry := range entries {
		if entry.IsDir() || !isRootProductionGoFile(entry.Name()) {
			continue
		}

		file, err := parser.ParseFile(fset, entry.Name(), nil, parser.ParseComments)
		if err != nil {
			t.Fatalf("parse %s: %v", entry.Name(), err)
		}
		issues = append(issues, exportedDocumentationIssues(fset, file, "gows")...)
	}

	if len(issues) != 0 {
		t.Fatalf("exported documentation contract violations:\n  %s", strings.Join(issues, "\n  "))
	}
}

func TestExportedDocumentationContractAcceptsSupportedDocumentationForms(t *testing.T) {
	tests := []struct{ name, source string }{
		{name: "one line", source: "package gows\n\n// Thing describes a value in one line.\ntype Thing struct{}\n"},
		{name: "multiline", source: "package gows\n\n// Thing describes a value across\n// multiple lines.\ntype Thing struct{}\n"},
		{name: "Go doc link", source: "package gows\n\n// Thing describes a value.\ntype Thing struct{}\n\n// Worker performs work using [Thing].\ntype Worker interface {\n\t// Work performs one unit of work.\n\tWork()\n}\n"},
		{name: "grouped declarations", source: "package gows\n\nconst (\n\t// DefaultThing is the default value.\n\tDefaultThing = 1\n)\n\ntype (\n\t// GroupedThing is a grouped type declaration.\n\tGroupedThing struct{}\n)\n"},
		{name: "directive", source: "package gows\n\n// NewThing constructs a value.\n//\n//go:noinline\nfunc NewThing() int { return 1 }\n"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if issues := documentationIssuesForSource(t, "fixture.go", test.source); len(issues) != 0 {
				t.Fatalf("documented declaration rejected: %v", issues)
			}
		})
	}
}

func TestExportedDocumentationContractRejectsInvalidDocumentation(t *testing.T) {
	tests := []struct {
		name   string
		source string
		want   string
	}{
		{
			name:   "missing comment",
			source: "package gows\n\ntype Missing struct{}\n",
			want:   "fixture.go:3 Missing: missing doc comment",
		},
		{
			name:   "detached comment",
			source: "package gows\n\n// Detached describes a value.\n\ntype Detached struct{}\n",
			want:   "fixture.go:5 Detached: missing doc comment",
		},
		{
			name:   "missing terminal period",
			source: "package gows\n\n// Unfinished lacks terminal punctuation\ntype Unfinished struct{}\n",
			want:   "fixture.go:4 Unfinished: doc comment must end with a period",
		},
		{
			name:   "undocumented field",
			source: "package gows\n\n// Container contains a value.\ntype Container struct {\n\tValue string\n}\n",
			want:   "fixture.go:5 Value: missing doc comment",
		},
		{
			name:   "undocumented method",
			source: "package gows\n\n// Worker performs work.\ntype Worker interface {\n\tWork()\n}\n",
			want:   "fixture.go:5 Work: missing doc comment",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			issues := documentationIssuesForSource(t, "fixture.go", test.source)
			if len(issues) != 1 || issues[0] != test.want {
				t.Fatalf("issues = %q, want [%q]", issues, test.want)
			}
		})
	}
}

func TestExportedDocumentationContractExcludesNonProductionFiles(t *testing.T) {
	for _, name := range []string{"fixture_test.go", "fixture.txt"} {
		if isRootProductionGoFile(name) {
			t.Errorf("isRootProductionGoFile(%q) = true", name)
		}
	}

	issues := documentationIssuesForSource(t, "generated.go", `// Code generated by fixture. DO NOT EDIT.
package gows

type MissingGeneratedComment struct{}
`)
	if len(issues) != 0 {
		t.Fatalf("generated file was checked: %v", issues)
	}

	issues = documentationIssuesForSource(t, "other.go", `package other

type MissingOtherPackageComment struct{}
`)
	if len(issues) != 0 {
		t.Fatalf("non-root package was checked: %v", issues)
	}
}

func documentationIssuesForSource(t *testing.T, name, source string) []string {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, name, source, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	return exportedDocumentationIssues(fset, file, "gows")
}

func exportedDocumentationIssues(fset *token.FileSet, file *ast.File, packageName string) []string {
	if file.Name.Name != packageName || ast.IsGenerated(file) {
		return nil
	}
	if _, err := doc.NewFromFiles(fset, []*ast.File{file}, packageName, doc.PreserveAST|doc.AllDecls|doc.AllMethods); err != nil {
		position := fset.Position(file.Package)
		return []string{fmt.Sprintf("%s:%d: extract package documentation: %v", filepath.Base(position.Filename), position.Line, err)}
	}

	var issues []string
	check := func(name *ast.Ident, doc *ast.CommentGroup) {
		if name == nil || !name.IsExported() {
			return
		}
		position := fset.Position(name.Pos())
		prefix := fmt.Sprintf("%s:%d", filepath.Base(position.Filename), position.Line)
		if doc == nil || strings.TrimSpace(doc.Text()) == "" {
			issues = append(issues, prefix+" "+name.Name+": missing doc comment")
			return
		}
		if !docCommentEndsWithPeriod(doc) {
			issues = append(issues, prefix+" "+name.Name+": doc comment must end with a period")
		}
	}

	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			check(declaration.Name, declaration.Doc)
		case *ast.GenDecl:
			for _, spec := range declaration.Specs {
				switch spec := spec.(type) {
				case *ast.TypeSpec:
					doc := spec.Doc
					if doc == nil && len(declaration.Specs) == 1 {
						doc = declaration.Doc
					}
					check(spec.Name, doc)
					checkFieldDocumentation(check, spec.Type)
				case *ast.ValueSpec:
					doc := spec.Doc
					if doc == nil && len(declaration.Specs) == 1 {
						doc = declaration.Doc
					}
					for _, name := range spec.Names {
						check(name, doc)
					}
				}
			}
		}
	}
	return issues
}

func docCommentEndsWithPeriod(group *ast.CommentGroup) bool {
	parsed := new(comment.Parser).Parse(group.Text())
	printer := new(comment.Printer)
	lastProse := ""
	var visit func([]comment.Block)
	visit = func(blocks []comment.Block) {
		for _, block := range blocks {
			switch block := block.(type) {
			case *comment.Paragraph:
				text := printer.Text(&comment.Doc{Content: []comment.Block{block}})
				lastProse = strings.TrimSpace(string(text))
			case *comment.List:
				for _, item := range block.Items {
					visit(item.Content)
				}
			}
		}
	}
	visit(parsed.Content)
	return strings.HasSuffix(lastProse, ".")
}

func checkFieldDocumentation(check func(*ast.Ident, *ast.CommentGroup), expression ast.Expr) {
	switch expression := expression.(type) {
	case *ast.StructType:
		for _, field := range expression.Fields.List {
			if len(field.Names) == 0 {
				check(embeddedFieldName(field.Type), field.Doc)
				continue
			}
			for _, name := range field.Names {
				check(name, field.Doc)
			}
		}
	case *ast.InterfaceType:
		for _, method := range expression.Methods.List {
			for _, name := range method.Names {
				check(name, method.Doc)
			}
		}
	}
}

func embeddedFieldName(expression ast.Expr) *ast.Ident {
	switch expression := expression.(type) {
	case *ast.Ident:
		return expression
	case *ast.SelectorExpr:
		return expression.Sel
	case *ast.StarExpr:
		return embeddedFieldName(expression.X)
	case *ast.IndexExpr:
		return embeddedFieldName(expression.X)
	case *ast.IndexListExpr:
		return embeddedFieldName(expression.X)
	default:
		return nil
	}
}

func isRootProductionGoFile(name string) bool {
	return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
}
