// Copyright 2026 The gows Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package httpx_test

import (
	"errors"
	"testing"

	"github.com/zchee/gows/internal/httpx"
)

// rfc6455Key and rfc6455Accept are the known-answer test vector from
// RFC 6455 §4.2.2.
const (
	rfc6455Key    = "dGhlIHNhbXBsZSBub25jZQ=="
	rfc6455Accept = "s3pPLMBiTxaQ9kYGzzhZRbK+xOo="
)

func TestAppendAcceptKnownVector(t *testing.T) {
	got := httpx.AppendAccept(nil, []byte(rfc6455Key))
	if string(got) != rfc6455Accept {
		t.Fatalf("AppendAccept(%q) = %q, want %q", rfc6455Key, got, rfc6455Accept)
	}
}

func TestAppendAcceptAppendsToExistingDst(t *testing.T) {
	dst := []byte("Sec-WebSocket-Accept: ")
	got := httpx.AppendAccept(dst, []byte(rfc6455Key))
	want := "Sec-WebSocket-Accept: " + rfc6455Accept
	if string(got) != want {
		t.Fatalf("AppendAccept(dst, %q) = %q, want %q", rfc6455Key, got, want)
	}
}

func TestAccept(t *testing.T) {
	tests := map[string]struct {
		key     string
		want    string
		wantErr error
	}{
		"success: known vector": {
			key:  rfc6455Key,
			want: rfc6455Accept,
		},
		"error: empty key": {
			key:     "",
			wantErr: httpx.ErrInvalidKeyLength,
		},
		"error: key too short": {
			key:     "dGhlIHNhbXBsZSBub25jZQ=",
			wantErr: httpx.ErrInvalidKeyLength,
		},
		"error: key too long": {
			key:     "dGhlIHNhbXBsZSBub25jZQ==A",
			wantErr: httpx.ErrInvalidKeyLength,
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			got, err := httpx.Accept([]byte(tt.key))
			if tt.wantErr != nil {
				if !errors.Is(err, tt.wantErr) {
					t.Fatalf("Accept(%q): err = %v, want %v", tt.key, err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("Accept(%q): unexpected error %v", tt.key, err)
			}
			if string(got) != tt.want {
				t.Fatalf("Accept(%q) = %q, want %q", tt.key, got, tt.want)
			}
		})
	}
}

func TestAppendKey(t *testing.T) {
	got, err := httpx.AppendKey(nil)
	if err != nil {
		t.Fatalf("AppendKey: unexpected error %v", err)
	}
	if len(got) != 24 {
		t.Fatalf("AppendKey: len = %d, want 24", len(got))
	}

	// Two calls must not produce the same nonce (crypto/rand entropy).
	got2, err := httpx.AppendKey(nil)
	if err != nil {
		t.Fatalf("AppendKey: unexpected error %v", err)
	}
	if string(got) == string(got2) {
		t.Fatalf("AppendKey produced identical output on successive calls: %q", got)
	}

	// A key generated by AppendKey must be accepted as a valid
	// Sec-WebSocket-Key by Accept (round-trip length/format check).
	if _, err := httpx.Accept(got); err != nil {
		t.Fatalf("Accept(AppendKey output): unexpected error %v", err)
	}
}

func TestAppendAcceptAllocs(t *testing.T) {
	key := []byte(rfc6455Key)
	dst := make([]byte, 0, 64)
	f := func() {
		dst = httpx.AppendAccept(dst[:0], key)
	}
	if avg := testing.AllocsPerRun(100, f); avg != 0 {
		t.Fatalf("AppendAccept: %.2f allocs/op, want 0", avg)
	}
}

func BenchmarkAppendAccept(b *testing.B) {
	key := []byte(rfc6455Key)
	dst := make([]byte, 0, 64)
	b.ReportAllocs()
	for b.Loop() {
		dst = httpx.AppendAccept(dst[:0], key)
	}
}
